DELETE ENCHERES;
DELETE RETRAITS;
DELETE ARTICLES_VENDUS;
DELETE CATEGORIES;
DELETE UTILISATEURS;

DBCC CHECKIDENT (ARTICLES_VENDUS, RESEED, 0);
DBCC CHECKIDENT (CATEGORIES, RESEED, 0);
DBCC CHECKIDENT (UTILISATEURS, RESEED, 0);





